name: Add Issues and PRs to Triage

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  debug:
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

  triage:
    needs: debug
    uses: smallstep/workflows/.github/workflows/triage.yml@main
    secrets: inherit
